# -*- coding: utf-8 -*-
"""cw5_zad2_fasta_folder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-UfSohBrw4z-7F5TNieMch07tw-MnEy
"""

#Zadanie 2.
#Utworz skrypt ktory jako argumenty przyjmuje sciezke do
#folderu gdzie znajduja sie pliki z sekwencjami DNA w formacie FASTA.
#Skrypt powinien zczytac kazdy plik i obliczyc dla kazdej sekwencji
#jej dlugosc oraz zawartosc poszczegolnych nukleotydow (A, T, C, G).
#Wyniki powinny zostac zapisane do pliku o nazwie sekwencji w nowo utworzonym folderze "wyniki".
#Pamietaj o obsludze wyjatkow:
# FileNotFoundError - gdy podany folder nie istnieje
#ValueError - gdy plik nie jest w formacie FASTA
#- Inne wyjatki, ktore moga sie pojawic podczas dzialania programu
import os
import sys

def read_fasta(file_path):
    """Wczytuje sekwencję z pliku FASTA i zwraca jej nazwę i sekwencję."""
    with open(file_path, "r") as f:
        lines = f.readlines()

    if not lines or not lines[0].startswith(">"):
        raise ValueError(f"Plik {file_path} nie jest w formacie FASTA.")

    seq_name = lines[0].strip().replace(">", "")
    sequence = "".join(line.strip() for line in lines[1:]).upper()

    return seq_name, sequence


def count_nucleotides(sequence):
    """Zwraca liczbę nukleotydów i długość sekwencji."""
    return {
        "length": len(sequence),
        "A": sequence.count("A"),
        "T": sequence.count("T"),
        "C": sequence.count("C"),
        "G": sequence.count("G")
    }


def main():
    if len(sys.argv) != 2:
        print("Użycie: python fasta_stats.py <ścieżka_do_folderu>")
        sys.exit(1)

    folder_path = sys.argv[1]

    if not os.path.isdir(folder_path):
        raise FileNotFoundError(f"Folder {folder_path} nie istnieje.")

    output_dir = os.path.join(folder_path, "wyniki")
    os.makedirs(output_dir, exist_ok=True)

    for filename in os.listdir(folder_path):
        if filename.lower().endswith((".fa", ".fasta")):
            file_path = os.path.join(folder_path, filename)

            try:
                seq_name, sequence = read_fasta(file_path)
                stats = count_nucleotides(sequence)

                output_file = os.path.join(output_dir, f"{seq_name}.txt")
                with open(output_file, "w") as out:
                    out.write(f"Nazwa sekwencji: {seq_name}\n")
                    out.write(f"Długość: {stats['length']}\n")
                    out.write(f"A: {stats['A']}\n")
                    out.write(f"T: {stats['T']}\n")
                    out.write(f"C: {stats['C']}\n")
                    out.write(f"G: {stats['G']}\n")

                print(f"Zapisano: {output_file}")

            except ValueError as ve:
                print(f"Błąd formatu: {ve}")
            except Exception as e:
                print(f"Nieoczekiwany błąd w pliku {filename}: {e}")

    print("Gotowe.")


if __name__ == "__main__":
    main()