# -*- coding: utf-8 -*-
"""cw5_zad2quadratic_eq_error.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buMFwpetyCnW5BMe9u0cVxL3MA2HDmrK
"""

#Zadanie 1.
#Napisz skrypt, który przyjmuje od użytkownika 3 liczby całkowite a,b,c następnie oblicza wyrażenie kwadratowe i zwraca jego pierwiastki. Pamiętaj o obsłudze wyjątków:
#- ValueError - gdy użytkownik poda coś innego niż liczbe całkowitą
#- ZeroDivisionError - gdy a = 0 (wtedy to nie jest wyrażenie kwadratowe)
#- Inne wyjątki, które mogą się pojawić podczas działania programu

#Skrypt powinien być uruchamialny z terminala w sposób:
#python3 nazwa_skryptu.py [a] [b] [c]
import sys
import math

class QuadraticEquationError(Exception):
    """Własny wyjątek dla błędów równania kwadratowego."""
    pass

def solve_quadratic_equation(a, b, c):
    """
    Oblicza pierwiastki równania kwadratowego ax^2 + bx + c = 0.
    Obsługuje przypadki dla zera, jednego lub dwóch rzeczywistych pierwiastków.
    """
    if a == 0:
        raise ZeroDivisionError("Współczynnik 'a' nie może być zerem w równaniu kwadratowym.")

    delta = b**2 - 4*a*c

    if delta > 0:
        x1 = (-b + math.sqrt(delta)) / (2*a)
        x2 = (-b - math.sqrt(delta)) / (2*a)
        return f"Równanie ma dwa różne miejsca zerowe: x1 = {x1}, x2 = {x2}."
    elif delta == 0:
        x = -b / (2*a)
        return f"Równanie ma jedno (podwójne) miejsce zerowe: x = {x} ({x}, {x} - to jest jakby (x1,x2), x1=x2)."
    else:
        return "Równanie nie ma miejsc zerowych w zbiorze liczb rzeczywistych."

def main():
    # W tym trybie, skrypt oczekuje argumentów z wiersza poleceń.
    # sys.argv[0] to nazwa skryptu, więc oczekujemy 4 elementów: nazwa_skryptu, a, b, c.
    if len(sys.argv) != 4:
        raise QuadraticEquationError('Użycie: python3 nazwa_skryptu.py [a] [b] [c]')

    try:
        a = int(sys.argv[1])
        b = int(sys.argv[2])
        c = int(sys.argv[3])
    except ValueError:
        raise ValueError("Wszystkie argumenty (a, b, c) muszą być liczbami całkowitymi.")

    print(f"Wprowadzone liczby to: a={a}, b={b}, c={c}")

    try:
        result = solve_quadratic_equation(a, b, c)
        print(result)
    except ZeroDivisionError as e:
        print(f"Błąd: {e}")
    except Exception as e:
        print(f"Wystąpił nieoczekiwany błąd: {e}")

if __name__ == "__main__":
    try:
        main()
    except (QuadraticEquationError, ValueError) as e:
        print(f"Błąd uruchomienia skryptu: {e}")