# -*- coding: utf-8 -*-
"""cw5_zad3_planer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_HO2FHwOfWNNZWVyA9l2pCMttyDWqUG
"""

#Zadanie 3.
#Napisz funkcje, która dostaje listę wydarzeń w formacie:
#[('Spotkanie',"2025-12-01 19:00),('Impreza', "2026-01-31 20:00")...]
#następnie z takiej listy parsuje daty, sortuje je rosnąco i zwraca użytkownikowi, dla każdego
#wydarzenia nazwę, datę, ile dni pozostało. Dodatkowo można uwzględnić jakiś komunikat, jeśli data już mineła.
#Oczekiwany output:
#Spotkanie pon 1 grudnia 2025 19:00 (za 12 dni)
import datetime

def process_events(events):
  """
  Parsuje listę wydarzeń z ciągami dat, sortuje je i wyświetla szczegóły wydarzeń.

  Args:
    events (list): Lista krotek, gdzie każda krotka to (nazwa_wydarzenia, ciąg_daty).
                   Przykład: [('Spotkanie', '2025-12-01 19:00'), ...]
  """
  processed_events = []
  for name, date_str in events:
    try:
      # Parsuj ciąg daty na obiekt datetime
      event_datetime = datetime.datetime.strptime(date_str, '%Y-%m-%d %H:%M')
      processed_events.append((name, event_datetime))
    except ValueError:
      print(f"Ostrzeżenie: Nie można sparsować daty dla wydarzenia '{name}': {date_str}. Pomijanie.")
      continue

  # Sortuj wydarzenia według daty
  processed_events.sort(key=lambda x: x[1])

  now = datetime.datetime.now()

  for name, event_dt in processed_events:
    time_difference = event_dt - now


    formatted_date = event_dt.strftime('%a %d %B %Y %H:%M') # np. 'Mon 01 December 2025 19:00'

    if event_dt.date() == now.date(): # Wydarzenie jest dziś
        total_seconds = time_difference.total_seconds()
        hours = int(abs(total_seconds) // 3600)
        minutes = int((abs(total_seconds) % 3600) // 60)

        time_str = []
        if hours > 0:
            time_str.append(f"{hours} godzin")
        if minutes > 0:
            time_str.append(f"{minutes} minut")

        if not time_str: # Mniej niż minuta
            if total_seconds > 0:
                status_message = "dziś, za chwilę"
            else:
                status_message = "dziś, przed chwilą"
        else:
            time_description = " i ".join(time_str)
            if total_seconds > 0:
                status_message = f"dziś, za {time_description}"
            else:
                status_message = f"dziś, {time_description} temu"

    elif time_difference.total_seconds() > 0: # Wydarzenie w przyszłości, ale nie dziś
        days_remaining = time_difference.days
        status_message = f"za {days_remaining} dni"
    else: # Wydarzenie w przeszłości, nie dziś
        days_passed = abs(time_difference.days)
        status_message = f"minęło {days_passed} dni temu"

    print(f"{name} {formatted_date} ({status_message})")

# Przykładowe użycie:
events_list = [
    ('Spotkanie', '2025-11-21 11:30'),
    ('Impreza', '2026-01-31 20:00'),
    ('Egzamin', '2025-11-20 10:30'),
    ('Urodziny', '2024-03-15 12:00'),
    ('Wakacje', '2026-12-25 09:00'),
]

process_events(events_list)